// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: protos/protobuf.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type State int32

const (
	// Default the state is unknown
	State_UNKNOWN State = 0
	// The command ran to completion
	State_COMPLETE State = 1
	// The command was stopped prematurely by Stop()
	State_STOPPED State = 2
	// There was an error starting the command
	State_ERROR State = 3
	// The command is running
	State_RUNNING State = 4
	// The command has not started yet
	State_PENDING State = 5
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "UNKNOWN",
		1: "COMPLETE",
		2: "STOPPED",
		3: "ERROR",
		4: "RUNNING",
		5: "PENDING",
	}
	State_value = map[string]int32{
		"UNKNOWN":  0,
		"COMPLETE": 1,
		"STOPPED":  2,
		"ERROR":    3,
		"RUNNING":  4,
		"PENDING":  5,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_protobuf_proto_enumTypes[0].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_protos_protobuf_proto_enumTypes[0]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_protos_protobuf_proto_rawDescGZIP(), []int{0}
}

type StartRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// command to execute
	Command string `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	// arguments to the command
	Args          []string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"` //
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_protos_protobuf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_protobuf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_protos_protobuf_proto_rawDescGZIP(), []int{0}
}

func (x *StartRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *StartRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type StartResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// return the command ID of started command
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartResponse) Reset() {
	*x = StartResponse{}
	mi := &file_protos_protobuf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResponse) ProtoMessage() {}

func (x *StartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_protobuf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResponse.ProtoReflect.Descriptor instead.
func (*StartResponse) Descriptor() ([]byte, []int) {
	return file_protos_protobuf_proto_rawDescGZIP(), []int{1}
}

func (x *StartResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type OutputRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the command to retrieve the output of
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputRequest) Reset() {
	*x = OutputRequest{}
	mi := &file_protos_protobuf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputRequest) ProtoMessage() {}

func (x *OutputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_protobuf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputRequest.ProtoReflect.Descriptor instead.
func (*OutputRequest) Descriptor() ([]byte, []int) {
	return file_protos_protobuf_proto_rawDescGZIP(), []int{2}
}

func (x *OutputRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type OutputResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// output of the command
	Output        []byte `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputResponse) Reset() {
	*x = OutputResponse{}
	mi := &file_protos_protobuf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputResponse) ProtoMessage() {}

func (x *OutputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_protobuf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputResponse.ProtoReflect.Descriptor instead.
func (*OutputResponse) Descriptor() ([]byte, []int) {
	return file_protos_protobuf_proto_rawDescGZIP(), []int{3}
}

func (x *OutputResponse) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

type StatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id of the command to status
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_protos_protobuf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_protobuf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_protos_protobuf_proto_rawDescGZIP(), []int{4}
}

func (x *StatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// command ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// command which was executed
	Cmd string `protobuf:"bytes,2,opt,name=cmd,proto3" json:"cmd,omitempty"`
	// args to the command
	Args []string `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	// current state of the command
	State State `protobuf:"varint,4,opt,name=state,proto3,enum=cmd.State" json:"state,omitempty"`
	// exit status of the command
	Exit          int32 `protobuf:"varint,6,opt,name=exit,proto3" json:"exit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_protos_protobuf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_protobuf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_protos_protobuf_proto_rawDescGZIP(), []int{5}
}

func (x *StatusResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StatusResponse) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *StatusResponse) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *StatusResponse) GetState() State {
	if x != nil {
		return x.State
	}
	return State_UNKNOWN
}

func (x *StatusResponse) GetExit() int32 {
	if x != nil {
		return x.Exit
	}
	return 0
}

type StopRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the command to stop
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_protos_protobuf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_protobuf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_protos_protobuf_proto_rawDescGZIP(), []int{6}
}

func (x *StopRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StopResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the command stopped
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_protos_protobuf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_protobuf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_protos_protobuf_proto_rawDescGZIP(), []int{7}
}

func (x *StopResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_protos_protobuf_proto protoreflect.FileDescriptor

const file_protos_protobuf_proto_rawDesc = "" +
	"\n" +
	"\x15protos/protobuf.proto\x12\x03cmd\"<\n" +
	"\fStartRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\"\x1f\n" +
	"\rStartResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1f\n" +
	"\rOutputRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"(\n" +
	"\x0eOutputResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\fR\x06output\"\x1f\n" +
	"\rStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"|\n" +
	"\x0eStatusResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03cmd\x18\x02 \x01(\tR\x03cmd\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x12 \n" +
	"\x05state\x18\x04 \x01(\x0e2\n" +
	".cmd.StateR\x05state\x12\x12\n" +
	"\x04exit\x18\x06 \x01(\x05R\x04exit\"\x1d\n" +
	"\vStopRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1e\n" +
	"\fStopResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id*T\n" +
	"\x05State\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\f\n" +
	"\bCOMPLETE\x10\x01\x12\v\n" +
	"\aSTOPPED\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x03\x12\v\n" +
	"\aRUNNING\x10\x04\x12\v\n" +
	"\aPENDING\x10\x052\xcc\x01\n" +
	"\x05Agent\x12.\n" +
	"\x05Start\x12\x11.cmd.StartRequest\x1a\x12.cmd.StartResponse\x123\n" +
	"\x06Output\x12\x12.cmd.OutputRequest\x1a\x13.cmd.OutputResponse0\x01\x121\n" +
	"\x06Status\x12\x12.cmd.StatusRequest\x1a\x13.cmd.StatusResponse\x12+\n" +
	"\x04Stop\x12\x10.cmd.StopRequest\x1a\x11.cmd.StopResponseB,Z*github.com/stewyb314/remote-control/protosb\x06proto3"

var (
	file_protos_protobuf_proto_rawDescOnce sync.Once
	file_protos_protobuf_proto_rawDescData []byte
)

func file_protos_protobuf_proto_rawDescGZIP() []byte {
	file_protos_protobuf_proto_rawDescOnce.Do(func() {
		file_protos_protobuf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_protobuf_proto_rawDesc), len(file_protos_protobuf_proto_rawDesc)))
	})
	return file_protos_protobuf_proto_rawDescData
}

var file_protos_protobuf_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_protobuf_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_protos_protobuf_proto_goTypes = []any{
	(State)(0),             // 0: cmd.State
	(*StartRequest)(nil),   // 1: cmd.StartRequest
	(*StartResponse)(nil),  // 2: cmd.StartResponse
	(*OutputRequest)(nil),  // 3: cmd.OutputRequest
	(*OutputResponse)(nil), // 4: cmd.OutputResponse
	(*StatusRequest)(nil),  // 5: cmd.StatusRequest
	(*StatusResponse)(nil), // 6: cmd.StatusResponse
	(*StopRequest)(nil),    // 7: cmd.StopRequest
	(*StopResponse)(nil),   // 8: cmd.StopResponse
}
var file_protos_protobuf_proto_depIdxs = []int32{
	0, // 0: cmd.StatusResponse.state:type_name -> cmd.State
	1, // 1: cmd.Agent.Start:input_type -> cmd.StartRequest
	3, // 2: cmd.Agent.Output:input_type -> cmd.OutputRequest
	5, // 3: cmd.Agent.Status:input_type -> cmd.StatusRequest
	7, // 4: cmd.Agent.Stop:input_type -> cmd.StopRequest
	2, // 5: cmd.Agent.Start:output_type -> cmd.StartResponse
	4, // 6: cmd.Agent.Output:output_type -> cmd.OutputResponse
	6, // 7: cmd.Agent.Status:output_type -> cmd.StatusResponse
	8, // 8: cmd.Agent.Stop:output_type -> cmd.StopResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_protobuf_proto_init() }
func file_protos_protobuf_proto_init() {
	if File_protos_protobuf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_protobuf_proto_rawDesc), len(file_protos_protobuf_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_protobuf_proto_goTypes,
		DependencyIndexes: file_protos_protobuf_proto_depIdxs,
		EnumInfos:         file_protos_protobuf_proto_enumTypes,
		MessageInfos:      file_protos_protobuf_proto_msgTypes,
	}.Build()
	File_protos_protobuf_proto = out.File
	file_protos_protobuf_proto_goTypes = nil
	file_protos_protobuf_proto_depIdxs = nil
}
